client/.gitignore, client/package-lock.json, client/package.json, client/src/App.js, client/src/components/ClassificationsPage.jsx, client/src/components/Footer.jsx, client/src/components/Header.jsx
- Added placeholder header and footer.
- Started classifications page.
- Created generic links (to be updated) within BrowserRouter in App.js
=> Freds branch

client/src/PlacesToGo.jsx
chucking up PlacesToGo for the second time
=> proof of concept for PlacesToGo

client/src/App.js, client/src/components/pages/MeetTheTeamPage.jsx, client/src/components/pages/PaymentPage.jsx, client/src/components/structure/Header.jsx
- Started PaymentPage.jsx
- Updated MeetTheTeams.jsx to include all GitHub links.
- Update App.js to have the payment page path.
- Added payment button to header.
=> started payment page and updated MeetTheTeams

client/src/components/pages/PaymentPage.jsx
- Added 3rd party payment popup window.
- Input fields are now required to be filled.
=> Payment page

client/src/components/misc/PaymentSuccess.jsx, client/src/components/pages/PaymentPage.jsx
Added misc component folder
Added paySuccess component
=> created PaySuccess component and misc component folder

client/src/components/pages/BookingPage.jsx
- added booking page with axios functionality
=> started BookingPage with axios

client/src/App.js, client/src/components/pages/BookingPage.jsx, client/src/components/pages/DiscussionBoard.jsx, client/src/components/structure/Header.jsx
- Started Discussion Board.
- Updated Booking Page to reflect null values.
- Updated Header and App.js to allow for navigation to both pages.
=> added Discussion Board and updated App.js and Header.jsx

client/src/components/structure/Header.jsx
=> quick update to header

api/controller/discussionController.js, api/index.js, api/model/discussionModel.js
- Set-up Discussion API backend
=> set up Discussion backend using express

api/controller/discussionController.js, client/src/components/misc/DiscussionPrinter.jsx, client/src/components/pages/DiscussionBoard.jsx
- Changing selected movie instantly loads relevant discussion posts.
=> made good progress on Discussions board

api/controller/discussionController.js
Very quick change to enable delete functionality of discussion controller
=> fixed discussion controller

api/controller/discussionController.js, api/model/discussionModel.js, client/package-lock.json, client/package.json, client/src/components/misc/DiscussionPrinter.jsx, client/src/components/pages/DiscussionBoard.jsx, package-lock.json, package.json
- added profanity-filter
- added rating for movies
=> Profanity filter

client/src/components/misc/DiscussionForm.jsx, client/src/components/misc/DiscussionPrinter.jsx, client/src/components/pages/DiscussionBoard.jsx
- Moved discuss form to another Component for readability's sake.
- Prevented the user from making multiple accidental posts.
- Posts will now automatically update with user's new post.
=> greatly improved readability and function of discussionboard

api/controller/discussionController.js, client/package-lock.json, client/package.json, client/src/components/pages/DiscussionBoard.jsx
now cleans the input rather than preventing it
=> basic profanity filtering

api/controller/MovieBookingController.js, api/routes/Bookings.js, client/src/components/misc/BookingPrinter.jsx, client/src/components/misc/PaymentSuccess.jsx, client/src/components/pages/DiscussionBoard.jsx, client/src/components/pages/PaymentPage.jsx
- Payment now links to DB
- Has multiple conditionals to make the page as interactive as possible.
- Updated bookings controller to allow for new search criteria.
- fixed discussion board a little bit
=> big improvements to the payment page

api/config/testconfig.env, api/index.js
- Local DB and Test DB are now switched by changing one string
=> enabled testing db on local machine

client/src/components/pages/PaymentPage.jsx, test/qacinemastest/src/test/java/com/qa/PaymentPageTests.java
Added selenium testing for payment page
=> added payment page selenium testing

test/qacinemastest/src/test/java/com/qa/ClassificationsPageTest.java
Added nav and load test from homepage to classifications
=> added classifications test from home

test/qacinemastest/src/test/java/com/qa/DiscussionsPageTest.java
=> added discussions page testing

test/qacinemastest/src/test/java/com/qa/ScreensPageTest.java
=> added screens page test
